### ISSUE TITLE
Use CI

### ISSUE THREAD

**Issue by tdutrion** [enl/flysystem-cloudinary#2]
Hi,

Could you enable the project both on [travis-ci](https://travis-ci.org) and [coveralls](https://coveralls.io), so all the tests and coverage are automatically triggered?

I have already started to work on the configurations here: [engineor/flysystem-cloudinary](https://github.com/engineor/flysystem-cloudinary), and as soon as you enable both of them I'll be able to change the links and create a PR (style and ci config only for now).

**Comment by enl** [comment]
I've just enabled the project on travis and coveralls, you're wellcome to create a PRs :)

**Comment by tdutrion** [comment]
Badges included in README in PR #4.
