### ISSUE TITLE
Delete not working for me

### ISSUE THREAD

**Issue by leeovery** [enl/flysystem-cloudinary#8]
Hi,

The delete method isn't working for me. It seems to fail on the method where you normalizeMetaData as a result of calling the has method. The FlySystem delete method does the 'has' check before deleting.

The has method calls to the getMetadata method, which in turn grabs the resource via the Cloudinary API, and then the result of that is passed to the normalizeMetadata method.

The normalizeMetadata method receives a Cloudinary\Api\Response, but if that parameter is not an array, then the normalizeMetadata method simply returns false. This obviously rattles back up the chain and results in the has method returning false, meaning the file wasnt found, meaning the delete method doesnt get called.

Am I missing something here or is this a bug?

Thanks
Lee

**Comment by leeovery** [comment]
To update, I got it working by changing the normalizeMetadata method to:

```
private function normalizeMetadata($resource)
    {
        return !$resource instanceof \ArrayObject ? false : [
            'type' => 'file',
            'path' => $resource['public_id'],
            'size' => array_key_exists('bytes', $resource) ? $resource['bytes'] : false,
            'timestamp' => array_key_exists('created_at', $resource) ? strtotime($resource['created_at']) : false,
        ];
    }
```

Can you make this fix? Or would you prefer a pull request?

**Comment by enl** [comment]
Hi @leeovery, thx for reporting and fix snippet. 

I'll investigate the problem a bit and publish new version as soon as I do fix. BTW, pull request will be useful too :+1:

**Comment by leeovery** [comment]
#9 done :)
